"""criação das tabelas bands, albuns e musics

Revision ID: 440fb0d68b9c
Revises: 
Create Date: 2022-04-14 18:23:46.054589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440fb0d68b9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bands',
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('band_id')
    )
    op.create_table('albums',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['bands.band_id'], ),
    sa.PrimaryKeyConstraint('album_id')
    )
    op.create_table('musics',
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('duration', sa.Time(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.PrimaryKeyConstraint('music_id')
    )
    op.drop_table('membros_db')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membros_db',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cpf', sa.CHAR(length=11), autoincrement=False, nullable=True),
    sa.Column('data_registro', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='membros_db_pkey'),
    sa.UniqueConstraint('cpf', name='membros_db_cpf_key')
    )
    op.drop_table('musics')
    op.drop_table('albums')
    op.drop_table('bands')
    # ### end Alembic commands ###
